name: amicae
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  http:
  flutter_widget_from_html_core: ^0.15.2
  flutter_map: any

  firebase_database: ^11.3.4
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.1
  latlong2: ^0.9.1
  intl: ^0.17.0
  google_fonts: ^6.2.1
  geolocator: ^13.0.3  # Updated geolocator version
  provider: ^6.1.2  # Added for state management
  firebase_vertexai: ^1.5.0
  


dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  mockito: ^5.4.4
  build_runner: ^2.4.8

  flutter_test:
    sdk: flutter
  test: ^1.16.0 # to add the test package


  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/ae_short_black.png
    - assets/ae_short_white.png
    - assets/ae_long_black.png
    - assets/ae_long_white.png
    - assets/temp_avatars/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/short_logo_light.png"
